/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.test {
    export class BigUI extends Laya.Scene {
		public _list:Laya.List;
        public static  uiView:any ={"type":"Scene","props":{"x":0,"width":600,"height":802},"compId":2,"child":[{"type":"List","props":{"y":0,"x":7,"width":600,"var":"_list","vScrollBarSkin":" ","spaceY":2,"repeatX":1,"height":649,"elasticEnabled":true},"compId":3,"child":[{"type":"bigItem","props":{"runtime":"view/bigItem.ts","renderType":"render"},"compId":5}]}],"loadList":[],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(BigUI.uiView);
        }
    }
    REG("ui.test.BigUI",BigUI);
    export class BigItemUI extends Laya.View {
		public img_head:Laya.Image;
		public text_name:Laya.Label;
        public static  uiView:any ={"type":"View","props":{"width":593,"height":122},"compId":2,"child":[{"type":"Sprite","props":{"y":0,"x":0,"width":593,"texture":"rank/排行栏.png","height":122},"compId":19},{"type":"Sprite","props":{"y":9.5,"x":109.5,"texture":"rank/头像框描边.png","name":"contour"},"compId":27},{"type":"Image","props":{"y":19,"x":117,"width":80,"var":"img_head","skin":"rank/头像.png","height":80},"compId":3,"child":[{"type":"Sprite","props":{"y":-4.5,"x":-4.5,"texture":"rank/头像框.png","renderType":"mask"},"compId":26}]},{"type":"Label","props":{"y":66,"x":284,"width":131,"var":"text_name","valign":"middle","text":"老王哥","strokeColor":"#3b5785","stroke":1,"pivotY":19,"pivotX":66,"overflow":"visible","height":38,"fontSize":29,"font":"Microsoft YaHei","color":"#3b5785","align":"left"},"compId":4},{"type":"FontClip","props":{"y":63,"x":470,"width":140,"value":"10000","spaceX":-5,"skin":"rank/分数字体.png","sheet":"0123456789","pivotY":19,"pivotX":70,"name":"text_score","height":37,"align":"center"},"compId":17},{"type":"Sprite","props":{"y":-2,"x":0,"name":"rankNum"},"compId":30,"child":[{"type":"Image","props":{"y":20,"x":16,"skin":"rank/NO1.png","name":"rankNum_pic"},"compId":32},{"type":"FontClip","props":{"y":64,"x":54,"width":70,"value":"99","spaceX":-9,"skin":"rank/排行字体.png","sheet":"0123456789","pivotY":23,"pivotX":35,"name":"rankNum_Num","height":45,"align":"center"},"compId":31}]}],"loadList":["rank/排行栏.png","rank/头像框描边.png","rank/头像.png","rank/头像框.png","rank/分数字体.png","rank/NO1.png","rank/排行字体.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(BigItemUI.uiView);
        }
    }
    REG("ui.test.BigItemUI",BigItemUI);
}