/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import Suspend from "./script/Suspend"
import Assembly from "./script/Assembly"
import Role from "./script/Role"
import OperationControl from "./script/OperationControl"
import MainSceneControl from "./script/MainSceneControl"
import Candy from "./script/Candy"
import Candy_Explode from "./script/Candy_Explode"
import Enemy from "./script/Enemy"
import EnemyBullet from "./script/EnemyBullet"
import EnemyHint from "./script/EnemyHint"
import Explode from "./script/Explode"
import HintWord from "./script/HintWord"
import Ranking from "./script/Ranking"
import Resurgence from "./script/Resurgence"
import RewardWords from "./script/RewardWords"
import RoleBullet from "./script/RoleBullet"
import Settlement from "./script/Settlement"
import StartGame from "./script/StartGame"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=750;
    static height:number=1334;
    static scaleMode:string="fixedwidth";
    static screenMode:string="vertical";
    static alignV:string="top";
    static alignH:string="center";
    static startScene:any="scene/MainScene.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=true;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("script/Suspend.ts",Suspend);
        reg("script/Assembly.ts",Assembly);
        reg("script/Role.ts",Role);
        reg("script/OperationControl.ts",OperationControl);
        reg("script/MainSceneControl.ts",MainSceneControl);
        reg("script/Candy.ts",Candy);
        reg("script/Candy_Explode.ts",Candy_Explode);
        reg("script/Enemy.ts",Enemy);
        reg("script/EnemyBullet.ts",EnemyBullet);
        reg("script/EnemyHint.ts",EnemyHint);
        reg("script/Explode.ts",Explode);
        reg("script/HintWord.ts",HintWord);
        reg("script/Ranking.ts",Ranking);
        reg("script/Resurgence.ts",Resurgence);
        reg("script/RewardWords.ts",RewardWords);
        reg("script/RoleBullet.ts",RoleBullet);
        reg("script/Settlement.ts",Settlement);
        reg("script/StartGame.ts",StartGame);
    }
}
GameConfig.init();